# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[(b'Contato', b'Contato'), (b'Movimento', b'Movimento'), (b'Pauta', b'Pauta')], max_length=150)),
                ('tel', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
