# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notas_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
