# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170306_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Movi'),
        ),
    ]
