# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170306_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 6, 13, 22, 22, 516416, tzinfo=utc)),
        ),
    ]
