# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_nota_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 6, 13, 30, 6, 861215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nota',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Movi'),
        ),
    ]
